package csd201_ws10_graph_dijkstra_upgrade_allshortestpath_dohuynhanhvu_ce171446;

import java.awt.*;
import java.awt.image.*;
import java.io.*;
import java.text.*;
import java.util.*;
import javax.imageio.*;
import javax.swing.*;
import javax.swing.filechooser.*;

/**
 *
 * @author Do Huynh Anh Vu - CE171446
 */
public class UndirectedGraph_FinalInterface extends javax.swing.JFrame {

    private GPaper p = null;
    JFileChooser fileChooser = new JFileChooser();
    SimpleDateFormat sdfDate = new SimpleDateFormat("yyyyMMdd_HHmmss");

    /**
     * Creates new form UndirectedGraph_DrawSaveOpenExport
     */
    public UndirectedGraph_FinalInterface() {
        initComponents();

        //set icon for JFrame
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/graph-icon.png")));

        //disable maximize button
        this.setResizable(false);

        //centering thr frame
        this.setLocationRelativeTo(null);

        p = new GPaper();
        p.setTxtGraphInfo(txtGraphInfo);
        pnlPaper.setLayout(new BorderLayout());
        pnlPaper.add(p, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GraphType = new javax.swing.ButtonGroup();
        labelGuide = new javax.swing.JLabel();
        pnlGraphInfo = new javax.swing.JPanel();
        rdbMatrix = new javax.swing.JRadioButton();
        rdbList = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGraphInfo = new javax.swing.JTextArea();
        pnlPaper = new javax.swing.JPanel();
        mnuMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniSave = new javax.swing.JMenu();
        mniSaveMatrix = new javax.swing.JMenuItem();
        mniList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuGraph = new javax.swing.JMenu();
        mniClear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniExport = new javax.swing.JMenuItem();
        mnuAlgorithm = new javax.swing.JMenu();
        mniSTP = new javax.swing.JMenuItem();
        mniSP = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniTraverse = new javax.swing.JMenu();
        mniBFS = new javax.swing.JMenuItem();
        mniDFS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UndirectedGraghDemoV1");

        labelGuide.setText("<html> ##### Draws vertices #####<br/>#1. Hold ctrl and click on space<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to add new vertex.<br/>#2. Hold shift and click on the vertex that you<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;want to remove.<br/>#3. Drag and drop the vertex to move it.<br/><br/>##### Draws edges #####<br/>#1. Select start vertex. <br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(click it again to unselected).<br/>#2. Select destination vertex.<br/>#3. Input edge'svalue.<br/>#4. Click on value of the exist edge to update.<html/>");

        pnlGraphInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph's Information"));

        GraphType.add(rdbMatrix);
        rdbMatrix.setSelected(true);
        rdbMatrix.setText("Matrix");
        rdbMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMatrixActionPerformed(evt);
            }
        });

        GraphType.add(rdbList);
        rdbList.setText("List");
        rdbList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbListActionPerformed(evt);
            }
        });

        txtGraphInfo.setEditable(false);
        txtGraphInfo.setColumns(18);
        txtGraphInfo.setRows(10);
        jScrollPane1.setViewportView(txtGraphInfo);

        javax.swing.GroupLayout pnlGraphInfoLayout = new javax.swing.GroupLayout(pnlGraphInfo);
        pnlGraphInfo.setLayout(pnlGraphInfoLayout);
        pnlGraphInfoLayout.setHorizontalGroup(
            pnlGraphInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGraphInfoLayout.createSequentialGroup()
                .addComponent(rdbMatrix)
                .addGap(55, 55, 55)
                .addComponent(rdbList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlGraphInfoLayout.setVerticalGroup(
            pnlGraphInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGraphInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGraphInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbMatrix)
                    .addComponent(rdbList, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPaper.setBorder(javax.swing.BorderFactory.createTitledBorder("Draw graph yourseft"));

        javax.swing.GroupLayout pnlPaperLayout = new javax.swing.GroupLayout(pnlPaper);
        pnlPaper.setLayout(pnlPaperLayout);
        pnlPaperLayout.setHorizontalGroup(
            pnlPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        pnlPaperLayout.setVerticalGroup(
            pnlPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mnuFile.setMnemonic('F');
        mnuFile.setText("File");

        mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        mniOpen.setMnemonic('O');
        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mniOpen);

        mniSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        mniSave.setMnemonic('S');
        mniSave.setText("Save as...");

        mniSaveMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniSaveMatrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/matrix.png"))); // NOI18N
        mniSaveMatrix.setMnemonic('M');
        mniSaveMatrix.setText("Matrix");
        mniSaveMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveMatrixActionPerformed(evt);
            }
        });
        mniSave.add(mniSaveMatrix);

        mniList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        mniList.setText("List");
        mniList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListActionPerformed(evt);
            }
        });
        mniSave.add(mniList);

        mnuFile.add(mniSave);
        mnuFile.add(jSeparator1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        mniExit.setMnemonic('E');
        mniExit.setText("Exit");
        mniExit.setToolTipText("");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnuMain.add(mnuFile);

        mnuGraph.setMnemonic('G');
        mnuGraph.setText("Graph");

        mniClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        mniClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        mniClear.setMnemonic('C');
        mniClear.setText("Clear");
        mniClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClearActionPerformed(evt);
            }
        });
        mnuGraph.add(mniClear);
        mnuGraph.add(jSeparator2);

        mniExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mniExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export.png"))); // NOI18N
        mniExport.setMnemonic('E');
        mniExport.setText("ExportPNG");
        mniExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExportActionPerformed(evt);
            }
        });
        mnuGraph.add(mniExport);

        mnuMain.add(mnuGraph);

        mnuAlgorithm.setMnemonic('A');
        mnuAlgorithm.setText("Algorithm");

        mniSTP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mniSTP.setMnemonic('H');
        mniSTP.setText("Finds shortest path");
        mniSTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSTPActionPerformed(evt);
            }
        });
        mnuAlgorithm.add(mniSTP);

        mniSP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mniSP.setMnemonic('M');
        mniSP.setText("Minimum spanning tree");
        mniSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSPActionPerformed(evt);
            }
        });
        mnuAlgorithm.add(mniSP);
        mnuAlgorithm.add(jSeparator3);

        mniTraverse.setText("Traversing...");

        mniBFS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mniBFS.setText("BFS");
        mniBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBFSActionPerformed(evt);
            }
        });
        mniTraverse.add(mniBFS);

        mniDFS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mniDFS.setText("DFS");
        mniDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDFSActionPerformed(evt);
            }
        });
        mniTraverse.add(mniDFS);

        mnuAlgorithm.add(mniTraverse);

        mnuMain.add(mnuAlgorithm);

        setJMenuBar(mnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelGuide)
                    .addComponent(pnlGraphInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGuide, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGraphInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public File getSaveFile(FileNameExtensionFilter filter, String filename) {
        fileChooser.setFileFilter(filter);
        fileChooser.setSelectedFile(new File(filename));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile().exists()) {
                int response = JOptionPane.showConfirmDialog(null, "Do you really want to replace the existing file ?", "Conform", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response != JOptionPane.YES_OPTION) {
                    return null;
                }
            }
            return fileChooser.getSelectedFile();
        }
        return null;
    }
    private void mniExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExportActionPerformed

        File saveFile = getSaveFile(new FileNameExtensionFilter("PNG image (*.png)", "png"), "export_" + sdfDate.format(Calendar.getInstance().getTime()) + ".png");
        if (saveFile != null) {
            BufferedImage image = new BufferedImage(p.getWidth(), p.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = image.createGraphics();
            p.printAll(g);

            g.setColor(Color.red);
            g.drawString("Đỗ Huỳnh Anh Vũ # SUMMER 2022 # CSD201 # SE1607", 10, 20);

            g.dispose();
            try {
                ImageIO.write(image, "png", saveFile);
            } catch (IOException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_mniExportActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mniExitActionPerformed

    private void rdbListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbListActionPerformed
        this.p.setGraphType(1);
    }//GEN-LAST:event_rdbListActionPerformed

    private void rdbMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMatrixActionPerformed
        this.p.setGraphType(0);
    }//GEN-LAST:event_rdbMatrixActionPerformed

    private void mniClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClearActionPerformed
        this.p.clear();
    }//GEN-LAST:event_mniClearActionPerformed

    private void mniSaveMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveMatrixActionPerformed
        File saveFile = getSaveFile(new FileNameExtensionFilter("Graph data (*.mtx)", "mtx"), "graph_" + sdfDate.format(Calendar.getInstance().getTime()) + ".mtx");
        //1 Cần lưu số lượng đỉnh của đồ thì (NumberofVertices)
        //2 Lưu tọa độ x,y của các đỉnh
        //3 ma trận trọng số
        if (saveFile != null) {
            if (saveFile.getName().endsWith(".mtx")) {
                ArrayList<GVertex> verties = p.getVertices();
                int[][] graph = p.getGraph();
                int numberOfVertex = p.getNumberOfVertices();
                FileWriter fw = null;
                String strData = "";
                String strXY = "";

                for (int i = 0; i < verties.size(); i++) {
                    strXY += "\n" + verties.get(i).getX() + " " + verties.get(i).getY();
                }

                try {
                    strData += numberOfVertex;
                    strData += strXY;
                    for (int i = 0; i < numberOfVertex; i++) {
                        strData += "\n" + graph[i][0];
                        for (int j = 1; j < numberOfVertex; j++) {
                            strData += " " + graph[i][j];
                        }
                    }
                    fw = new FileWriter(saveFile);
                    fw.write(strData);
                    fw.flush();
                    fw.close();
                } catch (IOException e) {
                    System.err.println(e);
                } finally {
                    try {
                        fw.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                }
            }
        }
    }//GEN-LAST:event_mniSaveMatrixActionPerformed

    private void mniListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListActionPerformed
        File saveFile = getSaveFile(new FileNameExtensionFilter("Graph data (*.lst)", "lst"), "graph_" + sdfDate.format(Calendar.getInstance().getTime()) + ".lst");

        if (saveFile != null) {
            if (saveFile.getName().endsWith(".lst")) {
                ArrayList<GVertex> verties = p.getVertices();
                int[][] graph = p.getGraph();
                int numberOfVertex = p.getNumberOfVertices();
                FileWriter fw = null;
                String strData = "";
                String strXY = "";

                for (int i = 0; i < verties.size(); i++) {
                    strXY += "\n" + verties.get(i).getX() + " " + verties.get(i).getY();
                }

                try {
                    int countEdge = 0;
                    for (int i = 0; i < numberOfVertex - 1; i++) {
                        for (int j = i + 1; j < numberOfVertex; j++) {
                            if (graph[i][j] > 0) {
                                strData += "\n" + i + " " + j + " " + graph[i][j];
                                ++countEdge;
                            }
                        }
                    }
                    strData = numberOfVertex + " " + countEdge + strXY + strData;
                    fw = new FileWriter(saveFile);
                    fw.write(strData);
                    fw.flush();
                    fw.close();
                } catch (IOException e) {
                    System.err.println(e);
                } finally {
                    try {
                        fw.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                }
            }
        }
    }//GEN-LAST:event_mniListActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        fileChooser.setFileFilter((new FileNameExtensionFilter("Graph data (*.lst,*.mtx)", "lst", "mtx")));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (!fileChooser.getSelectedFile().exists()) {
                return;
            }
            File openFile = fileChooser.getSelectedFile();
            if (openFile.getName().endsWith(".mtx")) {
                p.readMatrixDataFile(openFile);
            } else if (openFile.getName().endsWith(".lst")) {
                p.readListDataFile(openFile);
            }
        }
    }//GEN-LAST:event_mniOpenActionPerformed

    private void mniBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBFSActionPerformed
        p.BFS();
    }//GEN-LAST:event_mniBFSActionPerformed

    private void mniDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDFSActionPerformed
        p.DFS();    }//GEN-LAST:event_mniDFSActionPerformed

    private void mniSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSPActionPerformed
        p.Prim();
    }//GEN-LAST:event_mniSPActionPerformed

    private void mniSTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSTPActionPerformed
        p.Dijkstra();
    }//GEN-LAST:event_mniSTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UndirectedGraph_FinalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UndirectedGraph_FinalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UndirectedGraph_FinalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UndirectedGraph_FinalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UndirectedGraph_FinalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GraphType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel labelGuide;
    private javax.swing.JMenuItem mniBFS;
    private javax.swing.JMenuItem mniClear;
    private javax.swing.JMenuItem mniDFS;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniExport;
    private javax.swing.JMenuItem mniList;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSP;
    private javax.swing.JMenuItem mniSTP;
    private javax.swing.JMenu mniSave;
    private javax.swing.JMenuItem mniSaveMatrix;
    private javax.swing.JMenu mniTraverse;
    private javax.swing.JMenu mnuAlgorithm;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuGraph;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JPanel pnlGraphInfo;
    private javax.swing.JPanel pnlPaper;
    private javax.swing.JRadioButton rdbList;
    private javax.swing.JRadioButton rdbMatrix;
    private javax.swing.JTextArea txtGraphInfo;
    // End of variables declaration//GEN-END:variables
}
